### ISSUE TITLE
Clash with internal dependency

### ISSUE THREAD

**Issue by chrhaase** [Chowdhury-DSP/chowdsp_utils#514]
Hi, I'm trying out chowdsp for handling plugin parameters, which has been very pleasant. Thanks a lot for that!
One bump on the way, though: In my project I have another library that uses `moodycamel::ReaderWriterQueue`,  so with chowdsp included ReaderWriterQueue was effectively included twice and I got errors like this one:
```
In file included from C:\...\build-clangcl-debug\_deps\chowdsp-src\modules\plugin\chowdsp_plugin_state/Backend/chowdsp_ParameterListeners.h:14:
In file included from C:\...\build-clangcl-debug\_deps\chowdsp-src\modules\plugin\chowdsp_plugin_state/Backend/../../../dsp/chowdsp_dsp_data_structures/third_party/moodycamel/readerwriterqueue.h:7:
C:\...\build-clangcl-debug\_deps\chowdsp-src\modules\plugin\chowdsp_plugin_state/Backend/../../../dsp/chowdsp_dsp_data_structures/third_party/moodycamel/atomicops.h(94,6): error: redefinition of 'memory_order'
   94 | enum memory_order
      |      ^
C:\...\build-clangcl-debug\_deps\readerwriterqueue-src/atomicops.h(95,6): note: previous definition is here
   95 | enum memory_order {
      |      ^
```
Do you have any thoughts on how to solve this nicely?

**Comment by jatinchowdhury18** [comment]
Sure thing!

One idea for solving this issue would be to have a pre-processor definition, something like `CHOWDSP_INCLUDE_MOODYCAMEL`, which would be set to `1` by default, but if the user is supplying their own version of the library, then they could set it to `0`. In that case the user would also need to be careful to ensure that their moodycamel headers are included _before_ any chowdsp headers that would need to know about the types defined by the moodycamel headers. I guess the naming could also be "inverted", so the user would set `CHOWDSP_SKIP_INCLUDE_MOODYCAMEL=1` if they want to bring their own.

Another idea is to "re-namespace" the internally included dependency. So in that case `chowdsp_moodycamel::memory_order` would not conflict with `moodycamel::memory_order`. That said, this would be a bit cumbersome, and I imagine other problems could arise out of this.

That said, I haven't run into this issue with other internal dependencies like `xsimd` or `nlohmann::json`... as best as I can tell the only difference is that those libraries use `#ifndef` header guards rather than `#pragma once`. However, for that solution to work in this case, the header guards would need to be changed in both the chowdsp copy of the moodycamel files, as well as the conflicting copy.

I'm open to any of these solutions, or if you have other ideas I'd be happy to hear them as well. If you have a small example repository that demonstrates this problem, then maybe we could work it out together from there.

**Comment by chrhaase** [comment]
I've put together a very simple example [here](https://github.com/chrhaase/chowdsp-rtlog-clash-example).

Yeah, I think I like the pre-processor def solution is probably simple and clean.
It would be convenient not to have to include the headers at "right moment", so maybe we could do:
```cpp
#if  CHOWDSP_INCLUDE_MOODYCAMEL
#include "../path/to/internal/moodycamel"
#else
#include <readerwriterqueue.h>
#endif
```
And so the user could add their own moodycamel source to the include search path?

Another idea I had was to do something like this (copy/pasted from the rtlog CMakeLists)
```cmake
if(NOT TARGET readerwriterqueue)
    include(FetchContent)
    FetchContent_Declare(ReaderWriterQueue
        GIT_REPOSITORY https://github.com/cameron314/readerwriterqueue
    )
    FetchContent_MakeAvailable(ReaderWriterQueue)
endif()
```
That way, we wouldn't need any preprocessor def and all includes would just be `#include <readerwriterqueue.h>`. What do you of that?

Actually, I tried re-namespacing, but there's a few places in the moodycamel headers that prevented that, e.g. `readerwriterqueue.h:792`:
```cpp
    typedef ::moodycamel::ReaderWriterQueue<T, MAX_BLOCK_SIZE> ReaderWriterQueue;
            ^^
```

**Comment by jatinchowdhury18** [comment]
Awesome! The example repo is super helpful... I've made a commit to [this branch](https://github.com/Chowdhury-DSP/chowdsp_utils/compare/moodycamel-clash-fix) with a fix that appears to work in the example repo. The definition names are a bit wordier than I would like, but I haven't been able to think of anything better yet.

The `FetchContent` approach makes sense, and is probably the way to go if this were a cmake-only project. However, I do try to keep this project compatible with the Projucer as well, and that fix wouldn't really work for them :(.

**Comment by chrhaase** [comment]
That's perfect, thanks!
Just a thought: I guess one could go more automatic with `#if __has_include(<readerwriterqueue.h>)`? Tried it out [here](https://github.com/chrhaase/chowdsp_utils/commit/ea556addb8b438fa18ed370ccaeb656821dae481) and it works with the example. Maybe there are situations where it could cause headaches to not have the explicit control - I'm not sure.

I hadn't thought of the Projucer - but that makes sense.

**Comment by jatinchowdhury18** [comment]
Oh nice! I hadn't used `__has_include` before, but that definitely makes everything a bit neater. I guess there could be a situation where that manual control could be nice, but I figure if you've added a file to your include path, then you probably want to use it, so we should prefer that one.

**Comment by chrhaase** [comment]
Me neither actually, but I guess this is the kind of problem it's good for :)
